import "@/styles/globals.css";
import Footer from "@/components/footer";

export const metadata = {
    title: "Games",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <head>
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Gamificación</title>
            </head>
            <body className=
                      "bg-blue-100 bg-base min-h-screen flex flex-col">
            <main className="container mx-auto min-h-screen flex flex-col">
                {children}
            </main>
            <Footer />
            </body>
        </html>
    );
}