/**
 * Componente RootLayout
 *
 * Este componente define el diseño raíz de main de la aplicación
 *
 * @param {Object} props - Propiedades del componente.
 * @param {React.ReactNode} props.children - Contenido dinámico que se renderiza dentro del layout.
 * @returns {JSX.Element} - Estructura de diseño principal de la aplicación.
 */

import "../../styles/globals.css"; // Importación de estilos globales
import Footer from "@/components/footer"; // Componente Footer

// Metadatos del sitio
export const metadata = {
    title: "Gamificación", // Título por defecto de la página
    description: "Generated by create next app", // Descripción del sitio
};

export default function RootLayout({ children }) {
    return (
        /**
         * Estructura general del layout
         * - <html>: Etiqueta raíz que define el idioma.
         * - <head>: Contiene información de metadatos como codificación y título.
         * - <body>: Estructura del contenido, incluyendo estilos generales.
         */
        <html lang="es">
        <head>
            {/* Metadatos del documento */}
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Gamificación</title>
        </head>
        <body className="text-gray-900 bg-base min-h-screen flex flex-col">
        {/* Contenedor principal para el contenido dinámico */}
        <main className="container mx-auto min-h-screen flex flex-col">
            {children}
        </main>
        {/* Pie de página */}
        <Footer />
        </body>
        </html>
    );
}


